---
title: "TDA_vec"
output: html_document
date: "2024-05-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

R results for VPB vectorization

```{r}
library(TDAvec)
```

# Data Set


```{r}
N <- 100
set.seed(123)
# sample N points uniformly from unit circle and add Gaussian noise
X <- TDA::circleUnif(N,r=1) + rnorm(2*N,mean = 0,sd = 0.2)
plot(X[,1], X[,2], asp = 1)
write.csv(X, "./unitCircle.csv", row.names = FALSE)
```


```{r}
# compute a persistence diagram using the Rips filtration built on top of X
D <- TDA::ripsDiag(X,maxdimension = 1,maxscale = 2)$diagram 
DD <- D
# switch from the birth-death to the birth-persistence coordinates
D[,3] <- D[,3] - D[,2] 
colnames(D)[3] <- "Persistence"
write.csv(D, "./PD.csv", row.names = FALSE)
```

```{r}
scaleSeq = seq(0,2,length.out=11) # sequence of scale values
```

# ComputeVPB

```{r}
# construct one-dimensional grid of scale values
ySeqH0 <- unique(quantile(D[D[,1]==0,3],probs = seq(0,1,by=0.2))) 
# ySeqH0 <- scaleSeq
tau <- 0.3 # parameter in [0,1] which controls the size of blocks around each point of the diagram 
# compute VPB for homological dimension H_0
vpb0 <- computeVPB(D,homDim = 0,xSeq=NA,ySeqH0,tau)
write.csv(vpb0, "./vpb_0.csv", row.names = FALSE)

xSeqH1 <- unique(quantile(D[D[,1]==1,2],probs = seq(0,1,by=0.2)))
# xSeqH1 <- scaleSeq
ySeqH1 <- unique(quantile(D[D[,1]==1,3],probs = seq(0,1,by=0.2)))
# ySeqH1 <- scaleSeq
# compute VPB for homological dimension H_1
vpb1 <- computeVPB(D,homDim = 1,xSeqH1,ySeqH1,tau) 
write.csv(vpb1, "./vpb_1.csv", row.names = FALSE)
```

## computePL

```{r}
scaleSeq = seq(0,2,length.out=11) # sequence of scale values

# compute persistence landscape (PL) for homological dimension H_0 with order of landscape k=1
pl0 <- computePL(DD,homDim=0,scaleSeq,k=1)
write.csv(pl0, "./pl_0.csv", row.names = FALSE)

# compute persistence landscape (PL) for homological dimension H_1 with order of landscape k=1
pl1 <- computePL(DD, homDim=1, scaleSeq,k=1)
write.csv(pl1, "./pl_1.csv", row.names = FALSE)
```


## computePS

```{r}
scaleSeq = seq(0,2,length.out=11) # sequence of scale values

# compute persistence silhouette (PS) for homological dimension H_0
ps0 <- computePS(DD,homDim=0,scaleSeq,p=1)
write.csv(ps0, "./ps_0.csv", row.names = FALSE)

# compute persistence silhouette (PS) for homological dimension H_1
ps1 <- computePS(DD,homDim=1,scaleSeq,p=1)
write.csv(ps1, "./ps_1.csv", row.names = FALSE)
```

## computeNL


```{r}
scaleSeq = seq(0,2,length.out=11) # sequence of scale values

# compute persistence silhouette (PS) for homological dimension H_0
nl0 <- computeNL(DD,homDim=0,scaleSeq)
write.csv(nl0, "./nl_0.csv", row.names = FALSE)

# compute persistence silhouette (PS) for homological dimension H_1
nl1 <- computeNL(DD,homDim=1,scaleSeq)
write.csv(nl1, "./nl_1.csv", row.names = FALSE)
```

## computeVAB

```{r}
# compute vector of averaged Bettis (VAB) for homological dimension H_0
vab_0 <- computeVAB(DD,homDim=0,scaleSeq)
write.csv(vab_0, "./vab_0.csv", row.names = FALSE)

# compute vector of averaged Bettis (VAB) for homological dimension H_1
vab_1 <- computeVAB(DD,homDim=1,scaleSeq)
write.csv(vab_1, "./vab_1.csv", row.names = FALSE)
```

## computeECC

```{r}
# compute ECC
ecc_0 <- computeECC(DD, 0, scaleSeq)
write.csv(ecc_0, "./ecc_0.csv", row.names = FALSE)
ecc_1 <- computeECC(DD, 1, scaleSeq)
write.csv(ecc_1, "./ecc_1.csv", row.names = FALSE)
```

## computePES

```{r}
# compute ECC
pes_0 <- computePES(DD, 0, scaleSeq)
write.csv(pes_0, "./pes_0.csv", row.names = FALSE)
pes_1 <- computePES(DD, 1, scaleSeq)
write.csv(pes_1, "./pes_1.csv", row.names = FALSE)
```

## computePI

```{r}
resB <- 5 # resolution (or grid size) along the birth axis
resP <- 5 # resolution (or grid size) along the persistence axis 

# compute PI for homological dimension H_0
minPH0 <- min(D[D[,1]==0,3]); maxPH0 <- max(D[D[,1]==0,3])
ySeqH0 <- seq(minPH0,maxPH0,length.out=resP+1)
sigma <- 0.5*(maxPH0-minPH0)/resP 
pi0 <- computePI(D,homDim=0,xSeq=NA,ySeqH0,sigma) 
write.csv(pi0, "./pi_0.csv", row.names = FALSE)

# compute PI for homological dimension H_1
minBH1 <- min(D[D[,1]==1,2]); maxBH1 <- max(D[D[,1]==1,2])
minPH1 <- min(D[D[,1]==1,3]); maxPH1 <- max(D[D[,1]==1,3])
xSeqH1 <- seq(minBH1,maxBH1,length.out=resB+1)
ySeqH1 <- seq(minPH1,maxPH1,length.out=resP+1)
sigma <- 0.5*(maxPH1-minPH1)/resP
pi1 <- computePI(D,homDim=1,xSeqH1,ySeqH1,sigma) 
write.csv(pi1, "./pi_1.csv", row.names = FALSE)
```

## FDA

```{r}
# get min and max values of dim0 and dim1 reatures of the presistense diagrams from the list
findLimits <- function(D,homDim){
  # D: a list of PDs
  n <- length(D)
  findMax <- function(pd,homDim){
    pd <- pd[pd[,1]==homDim,2:3,drop=F] # extracting PD of dimension d
    if (nrow(pd)>0) c(min(pd[,1]),
                      max(pd[is.finite(pd[,2]),2]))
    else rep(NA,2)
  }
  # body
  minB <- numeric(length = n)
  maxD <- numeric(length = n)
  for (k in 1:n){
    ans <- findMax(D[[k]],homDim)
    minB[k] <- ans[1]
    maxD[k] <- ans[2]
  }
  ans <- c(min(minB,na.rm = T),
           max(maxD,na.rm = T))
  names(ans) <- c('minB','maxD')
  return(ans)
}

```


```{r}
# Computes FDA coefficients for the given PD
generateForierFdata <- function(D, homDim, K, funcs, type='betti'){
  nW <- length(funcs)
  n <- length(D)
  X <- array(dim = c(n, 2*K + 1 ,nW))
  bound <- findLimits(D, homDim)
  for (k in 1:n) {
    pd <- D[[k]]
    pd <- pd[pd[,1]==homDim,2:3,drop=F]
    b <- pd[,1]/bound['maxD']; d <- pd[,2]/bound['maxD']
    alpha <- d-b # persistence
    
    for (j in 0:(nW-1)) X[k,1,j+1] <- sum(funcs[[j+1]](b, d)*alpha)
    
    for (m in 1:K){
      c <- 2*m*pi
      if(type == "betti") {
        alphasin <- sin(c*d)-sin(c*b)
        alphacos <- cos(c*d)-cos(c*b)
        for (j in 0:(nW-1)){
          X[k,2*m,j+1] <- -sqrt(2)/c*sum(funcs[[j+1]](b, d)*alphacos)
          X[k,2*m+1,j+1] <- sqrt(2)/c*sum(funcs[[j+1]](b, d)*alphasin)
        }
      }
      else if(type == "silhouette") {
        alphacos <- sin(c*b) + sin(c*d) - 2*sin(c*(b+d)/2)
        alphasin <- cos(c*b) + cos(c*d) - 2*cos(c*(b+d)/2)
        for (j in 0:(nW-1)){
          cc <- -sqrt(2)/(c*c)
          X[k,2*m,j+1] <- cc*sum(funcs[[j+1]](b, d)*alphacos)
          X[k,2*m+1,j+1] <- cc*sum(funcs[[j+1]](b, d)*alphasin)
        }
      }
      else {
        cat("ERROR: unknown type ", type,"\n")
      }
    }
    
  }
  return(X)
}
```

```{r}
wFL <- list(
  "w0" = function(b, d) return(1)
)
```


```{r}
findLimits( list(DD), 1)
```


```{r}
fda_0 = generateForierFdata(list(DD), 0, 10, wFL)[1,,1]
fda_1 = generateForierFdata(list(DD), 1, 10, wFL)[1,,1]
fda <- c(fda_0, fda_1)
write.csv(fda_0, "./fda_0.csv", row.names = FALSE)
write.csv(fda_1, "./fda_1.csv", row.names = FALSE)
```

```{r}
generateForierFdata(list(DD), 1, 10, wFL)[,,1]
```

```{r}
dd1 = DD[DD[,1]==1,]
dd1 = dd1[order(-dd1[,2]),]
dd1
```


```{r}
plot(NA, xlim = c(0, length(fda_0)), ylim = c( min(fda), max(fda)))
points(fda_0, type="o")
points(fda_1, type="o", col="red")
```

